from .adversary import (
    AutoDiscoveryObservationAdversary,
    KnightianObservationAdversary,
    ObservationAdversary,
    ScoreBasedObservationAdversary,
    SelectiveObservationAdversary,
    StructuralBreakObservationAdversary,
    SurpriseDrivenObservationAdversary,
    TimeVaryingObservationAdversary,
)
from .config import Q1ObjectiveConfig
from .metrics import normalized_group_weights, worst_group_loss
from .mnar import (
    MNAR_VIEW_MODES,
    SyntheticMNARConfig,
    SyntheticMNARResult,
    apply_synthetic_mnar,
    build_proxy_labels,
    build_group_adversarial_mask,
    sample_group_mnar_mask,
    sample_score_mnar_mask,
)
from .objectives import (
    GroupSnapshot,
    compute_example_weights,
    compute_score_based_weights,
    empirical_risk,
    estimate_group_snapshot,
    observed_empirical_risk,
    robust_risk,
    score_based_risk,
)
from .uncertainty import (
    GroupedObservationUncertaintySet,
    HistoryAwareObservationUncertaintySet,
    KnightianObservationSet,
    ObservationUncertaintySet,
    ScoreBasedObservationSet,
    ScoreObservationUncertaintySet,
    SelectiveObservationSet,
    StructuralBreakAwareObservationUncertaintySet,
    StructuralBreakObservationSet,
    SurpriseAwareObservationUncertaintySet,
    SurpriseDrivenObservationSet,
    TimeVaryingObservationSet,
    TimeVaryingObservationUncertaintySet,
)
from .structural_breaks import RupturesStructuralBreakDetector, StructuralBreakDetectionResult

__all__ = [
    "AgricultureBenchmarkConfig",
    "AgricultureDecisionTraceSummary",
    "AgricultureReferencePolicySummary",
    "AgricultureBenchmarkSummary",
    "AgricultureBenchmarkSuiteSummary",
    "AutoDiscoveryObservationAdversary",
    "BaselineComparisonConfig",
    "GradientTrialResult",
    "GradientValidationConfig",
    "GradientValidationSummary",
    "GroupSnapshot",
    "HistoryAwareObservationUncertaintySet",
    "KnightianObservationAdversary",
    "KnightianObservationSet",
    "MethodSummary",
    "MNAR_VIEW_MODES",
    "MonteCarloConfig",
    "MonteCarloSummary",
    "ObservationAdversary",
    "ObservationUncertaintySet",
    "Q1ObjectiveConfig",
    "RupturesStructuralBreakDetector",
    "ScenarioComparisonSummary",
    "ScoreObservationUncertaintySet",
    "ScoreBasedObservationAdversary",
    "ScoreBasedObservationSet",
    "GroupedObservationUncertaintySet",
    "SelectiveObservationAdversary",
    "SelectiveObservationSet",
    "StructuralBreakAwareObservationUncertaintySet",
    "StructuralBreakDetectionResult",
    "StructuralBreakObservationAdversary",
    "StructuralBreakObservationSet",
    "SurpriseAwareObservationUncertaintySet",
    "SurpriseDrivenObservationAdversary",
    "SurpriseDrivenObservationSet",
    "SyntheticMNARConfig",
    "SyntheticMNARResult",
    "TrialResult",
    "TimeVaryingObservationAdversary",
    "TimeVaryingObservationSet",
    "TimeVaryingObservationUncertaintySet",
    "apply_synthetic_mnar",
    "build_group_adversarial_mask",
    "build_proxy_labels",
    "sample_group_mnar_mask",
    "sample_score_mnar_mask",
    "compute_example_weights",
    "compute_score_based_weights",
    "empirical_risk",
    "estimate_group_snapshot",
    "format_agriculture_benchmark_summary",
    "format_agriculture_benchmark_suite_summary",
    "run_agriculture_decision_trace",
    "normalized_group_weights",
    "observed_empirical_risk",
    "robust_risk",
    "score_based_risk",
    "run_agriculture_benchmark",
    "run_agriculture_benchmark_suite",
    "run_monte_carlo",
    "run_gradient_validation",
    "run_gradient_validation_suite",
    "train_robust_group_online",
    "train_robust_knightian",
    "train_robust_structural_break",
    "train_robust_surprise",
    "train_robust_time_varying",
    "train_robust_score_online",
    "run_baseline_comparison",
    "run_baseline_comparison_suite",
    "run_validation_suite",
    "worst_group_loss",
]


def __getattr__(name: str):
    if name in {
        "AgricultureBenchmarkConfig",
        "AgricultureDecisionTraceSummary",
        "AgricultureReferencePolicySummary",
        "AgricultureBenchmarkSummary",
        "AgricultureBenchmarkSuiteSummary",
        "BaselineComparisonConfig",
        "GradientTrialResult",
        "GradientValidationConfig",
        "GradientValidationSummary",
        "MethodSummary",
        "MonteCarloConfig",
        "MonteCarloSummary",
        "ScenarioComparisonSummary",
        "TrialResult",
        "format_agriculture_benchmark_summary",
        "format_agriculture_benchmark_suite_summary",
        "run_agriculture_benchmark",
        "run_agriculture_decision_trace",
        "run_agriculture_benchmark_suite",
        "run_baseline_comparison",
        "run_baseline_comparison_suite",
        "run_gradient_validation",
        "run_gradient_validation_suite",
        "train_robust_group_online",
        "train_robust_knightian",
        "train_robust_structural_break",
        "train_robust_surprise",
        "train_robust_time_varying",
        "train_robust_score_online",
        "run_monte_carlo",
        "run_validation_suite",
    }:
        from .ag_benchmark import (
            AgricultureBenchmarkConfig,
            AgricultureDecisionTraceSummary,
            AgricultureReferencePolicySummary,
            AgricultureBenchmarkSummary,
            AgricultureBenchmarkSuiteSummary,
            format_agriculture_benchmark_summary,
            format_agriculture_benchmark_suite_summary,
            run_agriculture_benchmark,
            run_agriculture_decision_trace,
            run_agriculture_benchmark_suite,
        )
        from .comparison import (
            BaselineComparisonConfig,
            MethodSummary,
            ScenarioComparisonSummary,
            run_baseline_comparison,
            run_baseline_comparison_suite,
        )
        from .gradient_validation import (
            GradientTrialResult,
            GradientValidationConfig,
            GradientValidationSummary,
            run_gradient_validation,
            run_gradient_validation_suite,
            train_robust_group_online,
            train_robust_knightian,
            train_robust_structural_break,
            train_robust_surprise,
            train_robust_time_varying,
            train_robust_score_online,
        )
        from .monte_carlo import (
            MonteCarloConfig,
            MonteCarloSummary,
            TrialResult,
            run_monte_carlo,
            run_validation_suite,
        )

        mapping = {
            "AgricultureBenchmarkConfig": AgricultureBenchmarkConfig,
            "AgricultureDecisionTraceSummary": AgricultureDecisionTraceSummary,
            "AgricultureReferencePolicySummary": AgricultureReferencePolicySummary,
            "AgricultureBenchmarkSummary": AgricultureBenchmarkSummary,
            "AgricultureBenchmarkSuiteSummary": AgricultureBenchmarkSuiteSummary,
            "BaselineComparisonConfig": BaselineComparisonConfig,
            "format_agriculture_benchmark_summary": format_agriculture_benchmark_summary,
            "format_agriculture_benchmark_suite_summary": format_agriculture_benchmark_suite_summary,
            "GradientTrialResult": GradientTrialResult,
            "GradientValidationConfig": GradientValidationConfig,
            "GradientValidationSummary": GradientValidationSummary,
            "MethodSummary": MethodSummary,
            "MonteCarloConfig": MonteCarloConfig,
            "MonteCarloSummary": MonteCarloSummary,
            "run_agriculture_benchmark": run_agriculture_benchmark,
            "run_agriculture_decision_trace": run_agriculture_decision_trace,
            "run_agriculture_benchmark_suite": run_agriculture_benchmark_suite,
            "ScenarioComparisonSummary": ScenarioComparisonSummary,
            "TrialResult": TrialResult,
            "run_baseline_comparison": run_baseline_comparison,
            "run_baseline_comparison_suite": run_baseline_comparison_suite,
            "run_gradient_validation": run_gradient_validation,
            "run_gradient_validation_suite": run_gradient_validation_suite,
            "train_robust_group_online": train_robust_group_online,
            "train_robust_knightian": train_robust_knightian,
            "train_robust_structural_break": train_robust_structural_break,
            "train_robust_surprise": train_robust_surprise,
            "train_robust_time_varying": train_robust_time_varying,
            "train_robust_score_online": train_robust_score_online,
            "run_monte_carlo": run_monte_carlo,
            "run_validation_suite": run_validation_suite,
        }
        return mapping[name]
    raise AttributeError(f"module 'minimax_core' has no attribute {name!r}")
